# This file reuses CC BY 4.0 licensed content from https://github.com/TeachBooks/template.

title: Differential equations
author: W.M. Schouten-Straatman from Delft University of Technology, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
execute:
  execute_notebooks: "off"

parse:
    myst_enable_extensions:
      ## don't forget to list any other extensions you want enabled,
      ## including those that are enabled by default!
      - colon_fence 
      - dollarmath
      - linkify
      - substitution
      - tasklist
      - amsmath
      - attrs_inline
    myst_dmath_double_inline: true
    myst_heading_anchors : 5

only_build_toc_files: true

html:
  baseurl :  "https://tudelft-prime-books.github.io/Differential-Equations/"

sphinx:
  config:
    metadata_figure_settings:
      license:
        substitute_missing: true
      date:
        substitute_missing: true
    language: en
    sphinx_indexed_defs_indexed_nodes: ['strong']
    tud_change_titlesize: true
    new_tab_link_show_external_link_icon: true
    visualized_auto_cluster: true
    numfig_secnum_depth: 2
    mathjax3_config:
      loader:
        load: ['[tex]/cancel']
      tex:
        packages:
          '[+]': ['cancel']
        inlineMath: [ ['$','$'], ['\(','\)'] ]
        displayMath: [ ['$$','$$'], ['\[','\]'] ]
        macros:
          "Re": ["\\operatorname{Re}\\left(#1\\right)",1]
          "Im": ["\\operatorname{Im}\\left(#1\\right)",1]
          "vect": ["\\mathbf{#1}",1]
          "vec": ["\\mathbf{#1}",1]
          "nicefrac": ["\\frac{#1}{#2}", 2]
          "R": "\\mathbb{R}"
          "C": "\\mathbb{C}"
          "norm": ["\\left\\Vert #1 \\right\\Vert",1]
          "ip" : "\\cdot"
          "cp": ["\\times "]
    inverter_all: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js # Required for live code: https://teachbooks.io/manual/features/live_code.html
    thebe_config:
      use_thebe_lite: true                           # Required for live code: https://teachbooks.io/manual/features/live_code.html
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"] # Exclude files which should not be accessible for live code: https://teachbooks.io/manual/features/live_code.html
    html_theme_options:
      logo:
        text: Differential equations
      repository_url: "https://github.com/TUDelft-PRIME-Books/Differential-Equations"
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true                                  # Required for live code: https://teachbooks.io/manual/features/live_code.html
    html_show_copyright: false                       # As the copyright is included in the author field
    html_last_updated_fmt: '%B %-d, %Y'              # Adds the date of the last update to the footer
  extra_extensions:                                  # Extra extensions to be used in the book
    - teachbooks_favourites
    - teachbooks_sphinx_grasple                      # Adds the Grasple exercises to your book 
    - sphinx_prime_applets                           # Adds the Prime applets to your book
    - sphinx_tudelft_theme                           # Adds the TU Delft theme to your book https://teachbooks.io/manual/external/Sphinx-TUDelft-theme/README.html
    - sphinx_indexed_definitions
    - sphinx_new_tab_link
    - sphinx_apa_references                     # For APA citations
    - sphinx_visualized

bibtex_bibfiles: 
  - references.bib